import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div className="flex place-items-center gap-4 bg-red-400 p-10">
          Powered by{' '}
          <Image
            src="/validationCloud.png"
            alt="Validation Cloud Logo"
            width={300}
            height={300}
            priority
          />
        </div>
        {children}
        <div className="flex justify-center bg-black w-full p-5">
          Developed by Camilo Aguero Botero
        </div>
      </body>
    </html>
  )
}
